spring:
  application:
    name: EUREKA-CLIENT
  boot:
    admin:
      client:
        url: http://admin-server:8089
  security:
    user:
      name: admin
      password: admin123456

server:
      port: 8761 #服务注册中心端口号

eureka:
  server:
    #中小规模下，自我保护模式坑比好处多，所以关闭它
    enable-self-preservation: false
    #主动失效检测间隔,配置成5秒
    eviction-interval-timer-in-ms: 5000
    response-cache-update-interval-ms: 3000
    #禁用readOnlyCacheMap
    use-read-only-response-cache: false
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
    hostname: eureka-server #服务注册中心IP地址
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: http://eureka-server:${server.port}/actuator/health
  #        health-check-url-path: http://localhost:${server.port}/actuator/health
#    hostname: 127.0.0.1 #服务注册中心IP地址
  client:
    registerWithEureka: true #是否向服务注册中心注册自己
    fetchRegistry: true #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
      instance:


# 在admin中允许扫描项目信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

ribbon:
  eureka:
    enabled: true
